blank_issues_enabled: false
contact_links:
  - name: ğŸ™ Ask The Developer
    url: https://twitter.com/warengonzaga
    about: Have a question? Let me know!
  - name: ğŸ§  Suggestion
    url: https://twitter.com/warengonzaga
    about: Have an idea or suggestion? Let me know!
  - name: ğŸ“š Documentation
    url: https://docs.warengonzaga.com/wrn-cleaner
    about: Official Documentation for WRN Cleaner
